const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 125,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Levis Denim',
      category: 'Pant',
      image: '/images/p2.jpg',
      price: 48,
      countInStock: 20,
      brand: 'levis',
      rating: 5,
      numReviews: 23,
      description: 'high stretch product',
    },
    {
      name: 'lee brill Pant',
      slug: 'lee-brill-pant',
      category: 'Pant',
      image: '/images/p3.jpg',
      price: 267,
      countInStock: 7,
      brand: 'lee cooper',
      rating: 4.6,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Raymond Formal Shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 3,
      countInStock: 12,
      brand: 'Raymond',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Polo Round Shirt',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 70,
      countInStock: 2,
      brand: 'Polo',
      rating: 4.2,
      numReviews: 11,
      description: 'high quality product',
    },
    {
      name: 'Adidas Jogger Pant',
      category: 'Pant',
      image: '/images/p6.jpg',
      price: 700,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 5,
      description: 'high quality product',
    },
    {
      name: 'Firebolt smart watch',
      slug: 'firebolt-smart-watch',
      category: 'watches',
      image: '/images/watch1.jpg',
      price: 1000,
      countInStock: 25,
      brand: 'Firebolt',
      rating: 5,
      numReviews: 34,
      description: 'high quality watch ',
    },
    {
      name: 'Pearl Jhumka',
      slug: 'peral-jhumki-jhumki-earing',
      category: 'Jwellery',
      image: '/images/j1.jpg',
      price: 1500,
      countInStock: 25,
      brand: 'Pearl',
      rating: 5,
      numReviews: 3,
      description: 'High class Earings ',
    },
  ],
};

export default data;
